// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdHp5z_8AfUOc8s8p-ab30lnkJ5OyCdQ0',
    appId: '1:962821068285:web:2bd22838ff5bcc02503594',
    messagingSenderId: '962821068285',
    projectId: 'home-ease-distribute',
    authDomain: 'home-ease-distribute.firebaseapp.com',
    storageBucket: 'home-ease-distribute.appspot.com',
    measurementId: 'G-BDBG9T2W47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbkJ9vmbaQHDFBdXUJdCrnS8qIm3yxSt0',
    appId: '1:962821068285:android:6b9c368869bc6cb2503594',
    messagingSenderId: '962821068285',
    projectId: 'home-ease-distribute',
    storageBucket: 'home-ease-distribute.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCww6kL5cxyH_6Er75FPDtoVCXKMKitAFc',
    appId: '1:962821068285:ios:581caf3390b35fd2503594',
    messagingSenderId: '962821068285',
    projectId: 'home-ease-distribute',
    storageBucket: 'home-ease-distribute.appspot.com',
    iosBundleId: 'com.example.homeEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCww6kL5cxyH_6Er75FPDtoVCXKMKitAFc',
    appId: '1:962821068285:ios:08b8a5786a65bb27503594',
    messagingSenderId: '962821068285',
    projectId: 'home-ease-distribute',
    storageBucket: 'home-ease-distribute.appspot.com',
    iosBundleId: 'com.example.homeEase.RunnerTests',
  );
}
